### ISSUE TITLE
Performance : SQL optimization.

### ISSUE THREAD

**Issue by coderkoala** [coderkoala/crap-news#3]
The optimization is horrendous right now for the front page. 

First, it pick up categories from the sources tree, then via relationships, fetches an arbitrary number of queries per category. The number of transaction, as one might be aware, increases the number of categories goes up.

A quick napkin math suggests me 36+ queries just to get the front page news. As of right now, there are 80+ queries running in the front page. That is alone alarming, and this is deteriorate the bigger the articles table gets. 

My approach: get rid of the relationship, and introduce the category column in the articles table as well. Migration script has to be written, but in the end, you could potentially, in the best case scenario, need a single query with maybe a union or two (to make sure to filter 15-20 latest news of the same category) in order to achieve this.

# Roadmap
 
* [ ] Rework relationship to only allow for mass assignment during cron/seeding.
* [ ] Migration table for articles to introduce category FK.
* [ ] Normalize the sources table, and introduce category as a FK instead of a string.
* [ ] Relation now involves category as the independent key, with category_id in articles and sources as dependent tables.
* [ ] Rewrite the artisan command and the SourceSeeder class to reflect the respective changes.
